### ISSUE TITLE
Using TabNavigation in a react native project causes undefined is not an object (evaluating 'navigation.registerNavigatorContext')

### ISSUE THREAD

**Issue by davidfekke** [exponent/ex-navigation#286]
I am getting the following error when I try use the TabNavigation in my React native app.

undefined is not an object (evaluating 'navigation.registerNavigatorContext')

I have uploaded the test project here;
https://github.com/davidfekke/AesomeProject

**Comment by MyGuySi** [comment]
I'm getting this too, can't find a solution yet

**Comment by ericvicenti** [comment]
I hit this as well. Looks like you simply need to wrap your component with a `<NavigationProvider router={MyRouter} />`

**Comment by MyGuySi** [comment]
@ericvicenti That fixed it, thanks for clearing that up!

**Comment by davidfekke** [comment]
That fixed it for me as well.
