### ISSUE TITLE
SharedElement transitions with transculent status bar

### ISSUE THREAD

**Issue by nehvaleem** [exponent/ex-navigation#320]
Hi,
I've stumbled upon a weird thing. When using sharedelement while status bar is set to transculent (android) the transition seems to flick a little bit at the beginning and the end.

I don't know a bit about internal mechanism but it seems that adding StatusBar.currentHeight to outputRange at line 86 of ExNavigationSharedElement.js fixes the problem (at least for me).

It would be great if someone would look at this :)

**Comment by skevy** [comment]
cc @janicduplessis

**Comment by janicduplessis** [comment]
Noticed this a while ago but never got to fixing it since the app I'm using this in isn't released on Android yet. Just posted a PR to fix it #321
