### ISSUE TITLE
Passing submit function to static navigationBar property

### ISSUE THREAD

**Issue by 0x6e6562** [exponent/ex-navigation#324]
I'd like to move a form submit control up to the navigation bar that is currently bound to an instance function:

```jsx
<TouchableHighlight onPress={this.onFormSubmit}>
  <Text>Next</Text>
</TouchableHighlight>
```

Since the `navigationBar` property is static, you don't have access to the current properties of the component.

You can however pass in route parameters to `renderRight` and you can also inject the navigator using `@withNavigation` to make the navigationBar more contextual.

Another option might be to use the redux store, but this feels a little heavyweight. Similarly, I'm not quite seeing the [event emitter pattern](https://github.com/brentvatne/ex-navigation-conditional-buttons-example) as a neat solution for this requirement.

So I was wondering if there is an idiomatic way on passing the `this.onFormSubmit(..)` function into the static navigationBar context?

Or am completely over-engineering this? Is there an easier way to render the control into the navigation bar?

**Comment by 0x6e6562** [comment]
I'm not sure whether this is giving myself enough rope to hang myself, but the following injection seems to work:

```js
componentDidMount() {
  this.props.navigator.updateCurrentRouteParams({
    submit: this.onFormSubmit
  });
}
```

Does this feel idiomatic?

**Comment by 0x6e6562** [comment]
Whilst the above does work in isolation, I'm not sure that it will be robust in a flow.

After pushing a component onto the stack, I needed to make the `updateCurrentRouteParams` run in the background:

```js
componentDidMount() {
  setTimeout(() => {
    this.props.navigator.updateCurrentRouteParams({
      submit: this.onFormSubmit
    })
  }, 1000);
}
```

However, this asynchrony appears to create unwanted side effects:

```
Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the FocusableComponent component.
```

So I think I might need to go back to the drawing board on this one.

**Comment by 0x6e6562** [comment]
So I've got a little further with this concept. All I really want the submit button is to propagate a user click. It turns out that event emitters can easily be embedded statically:

```js
_subscriptionNext: EventSubscription;

componentWillMount() {
  this._subscriptionNext = this.props.route.getEventEmitter().addListener('next', this.requestCode);
}

componentWillUnmount() {
  this._subscriptionNext.remove();
}

MyScreen.route = {
  navigationBar: {
    renderRight: (state: ExNavigationState) => {
      const { config: { eventEmitter }  } = state;
      return (
         <TouchableOpacity onPress={() => eventEmitter.emit('next')}>
          <Text>Next</Text>
         </TouchableOpacity>
      );
    }
  }
}
```

I'm not sure where the `setState(...)` warning is coming from, but I think that might need it's own issue.

I think the event emitter pattern is quite small and is probably more robust than updating the route parameters.

**Comment by sibelius** [comment]
@0x6e6562 take a look on my answer: https://github.com/exponent/ex-navigation/issues/235#issuecomment-259692956

**Comment by 0x6e6562** [comment]
@sibelius Many thanks for the heads up - #235  is precisely where I got the example from - all I did was to give an inline solution for anybody else that stumbles across this thread, to save them some time.

BTW do you think the `setState(...)` warning warrants it's own issue? I'm currently looking through the issues to see if this already has a solution.

**Comment by sibelius** [comment]
setState is another issue

**Comment by 0x6e6562** [comment]
OK, then we should close this issue probably. I'll try to create a reproducible version of the setState issue and attach that to an appropriate issue.
