### ISSUE TITLE
static route not available to wrapped components

### ISSUE THREAD

**Issue by JulianKingman** [exponent/ex-navigation#329]
OK, I think this is a problem with `static route`. I'm using a HOC (higher order component) to wrap my component with the `static route`. Basically, HOC wraps a component and exports it with the same name and properties, but also with new inherited properties. In this case I'm using `react-native-meteor` to include meteor data into the component. The problem is that once that's done, the route no longer registers (ie none of the properties in the route seem to take effect).

This issue is similar to #242

Ideas?

**Comment by satya164** [comment]
When you wrap it in the HOC in meteor it exports a totally new component I presume. Some HOCs like Relay actually copy all the static properties to workaround this. I don't think it's something ExNavigation can fix. You can use the method to specify properties as said in the linked issue.

**Comment by JulianKingman** [comment]
I see what you're saying. This seems to be a problem many people are having in the react ecosystem, for which there is not a great solution. For me, this solution doesn't quite work as I need to access props from the container, which can't be passed outside of it to an object as far as I know. Do you have an idea of how to do that?

**Comment by sibelius** [comment]
There is a package to do this, search react hoist static

**Comment by sibelius** [comment]
@JulianKingman use this one: https://github.com/mridgway/hoist-non-react-statics

**Comment by JulianKingman** [comment]
Thanks! Great suggestion. Now I just need to get data and functions to the static route property, I'll start with #235.

**Comment by JulianKingman** [comment]
For completeness sake, it looks like this: 
````javascript
export default hoistNonReactStatic(createContainer(() => {
  return {
    user: Meteor.user(),
  };
}, HomeContainer), HomeContainer);
````
