### ISSUE TITLE
how to remove raised nav bar on Android ?

### ISSUE THREAD

**Issue by ajonno** [exponent/ex-navigation#338]
hi, is it possible to make the nav bar flat on Android ? i wasn't sure which property to set for this. many thanks!

![image](https://cloud.githubusercontent.com/assets/3005269/21492164/080bfa50-cc56-11e6-8aa8-fddefe555fbe.png)

**Comment by kanzitdinov** [comment]
Yeah, just set `elevation: 0` for Android and `borderBottomWidth: 0` for iOS in nav bar style :)

**Comment by ajonno** [comment]
oh i didn't see anything in docs re an elevation property on the navigationBar object. that did it thanks!
