### ISSUE TITLE
DrawerNavigation Multiple item for the same Component

### ISSUE THREAD

**Issue by robertodias180** [exponent/ex-navigation#341]
My drawer navigation has several item that will filter a ListView, and others that will move to another Screen. 

I tried this but when user click Cat2 a new Component home seems to be created, since the view cont in debugger is doubled.

		<DrawerNavigation
		  drawerPosition="left"
		  initialItem="home"
		>
		  <DrawerNavigationItem
		    id="home"
		    renderTitle={Cat1}
		  >
		    <StackNavigation
		      id="root"
		      defaultRouteConfig={DefaultRouteConfig}
		      initialRoute={Router.getRoute('home')}
		    />
		  </DrawerNavigationItem>
		  <DrawerNavigationItem
		    id="Cat2"
		    renderTitle={Cat2}
		  >
		  </DrawerNavigationItem>
		    <StackNavigation
		      id="root"
		      defaultRouteConfig={DefaultRouteConfig}
		      initialRoute={Router.getRoute('home')}
		    />
		  <DrawerNavigationItem
		    id="options"
		    renderTitle={Otions}
		  >
		    <StackNavigation
		      id="options"
		      defaultRouteConfig={DefaultRouteConfig}
		      initialRoute={Router.getRoute('options')}
		    />
		  </DrawerNavigationItem>
		</DrawerNavigation>

**Comment by sibelius** [comment]
u can render a custom drawer menu using this `renderNavigationView`: https://github.com/exponent/ex-navigation/blob/master/src/drawer/ExNavigationDrawer.js#L65

**Comment by robertodias180** [comment]
@sibelius  is there any examples of this?

**Comment by sibelius** [comment]
U can return any component

**Comment by robertodias180** [comment]
@sibelius  but who do i get the reference for

	    <StackNavigation
	      id="root"
	      defaultRouteConfig={DefaultRouteConfig}
	      initialRoute={Router.getRoute('home')}
	    />

**Comment by sibelius** [comment]
https://github.com/brentvatne/movieapp/blob/master/screens/DrawerNavigationScreen.js

**Comment by robertodias180** [comment]
thanks @sibelius i seem to made it work. But it fells like to much work for something so simple and common. This should be something to add in the future.

**Comment by robertodias180** [comment]
@sibelius one last question. What is be best way to swap between the multiple `StackNavigation` that i have?

**Comment by sibelius** [comment]
Just render a custom navigation Drawer and have only one stack navigation

**Comment by robertodias180** [comment]
the problem is that i need 2 stack views.

**Comment by sibelius** [comment]
One click of an item u could push the view inside the same stack

using 2 stacks can confuse the user

**Comment by robertodias180** [comment]
I will change the behaviour then. Thanks.
