### ISSUE TITLE
Nested navigators

### ISSUE THREAD

**Issue by piotrblasiak** [exponent/ex-navigation#342]
Is there any example with nested navigators?

When I try to do NavigatorProvider -> StackNavigation -> NavigatorProvider -> StackNavigation I get "Navigator does not exist".

**Comment by chirag04** [comment]
No need for addditinal navigation provider.

Navigation provider - stack navigator - stack navigator should work fine

**Comment by piotrblasiak** [comment]
That was it, thanks!
