### ISSUE TITLE
Can't add shadow to Navbar

### ISSUE THREAD

**Issue by JulianKingman** [exponent/ex-navigation#346]
I'm attempting to add a shadow to the navigationBar, but seem to be unable to do so. It looks like this:

````javascript
defaultRouteConfig = { 
    navigationBar: {
      backgroundColor: 'blue',
      tintColor: 'white',
      borderBottomColor: 'transparent',
      elevation: 1,
      shadowColor: '#000000',
      shadowOpacity: 0.3,
      shadowRadius: 2,
      zIndex: elevation,
      shadowOffset: {
        height: 2,
        width: 0,
      },
      titleStyle: {
        fontSize: 16,
        fontWeight: 'normal',
        textAlign: 'left',
        marginLeft: 40,
      },
    },
}
````

Browsing through the source code, it seems like only certain styles are allowed?

**Comment by JulianKingman** [comment]
Update: if I try to add styles via the `styles` param, I get:
````
this.props.interpolator.forContainer is not a function
````

**Comment by brentvatne** [comment]
`styles` is for transition styles, it probably should have been called `transitionStyles` instead

**Comment by JulianKingman** [comment]
Yeah, it would be handy if I could pass styles to the component. I figured out how to do this by adding a `View` to the `renderBackground` with a shadow. I think it's more complicated than it needs to be, but it works.
