### ISSUE TITLE
What will the difference be between ex-navigation and the Navigation component on the RN roadmap?

### ISSUE THREAD

**Issue by faceyspacey** [exponent/ex-navigation#350]
I'm referring to the `Navigation` component mentioned in the react-native roadmap here: https://github.com/facebook/react-native/wiki/Roadmap

Basically, if you're building with ex-navigation how easy will the migration strategy be? What will it look like? 

It would be nice to see some API docs for it so we can prepare for the transition, as this seems to be what will be the longest-lasting (reads: *final*) answer to the complex navigation problem. 

Also, what's its status? A month ago it's ETA changed from November to December. I can't find the `Navigation` component being worked on in the wild anywhere. @skevy and @ericvicenti any information on this much anticipated component? Anything maybe we can look at and possibly contribute to?

**Comment by faceyspacey** [comment]
no update?? @brentvatne  @skevy @ericvicenti

**Comment by tlvenn** [comment]
Would be awesome also to get an update an the tentative beta release of react-navigation in January given we are already the 15th. Thanks in advance guys !

**Comment by pothibo** [comment]
I believe the implementation of RN Navigation component is located here https://github.com/facebook/react-native/tree/master/Libraries/CustomComponents/NavigationExperimental

**Comment by satya164** [comment]
@faceyspacey https://github.com/exponent/ex-navigation#an-important-note-about-the-future

@tlvenn I can only say that it's very close to a beta release.

@pothibo No. It's an implementation of NavigationExperimental which is used in the new navigation library.

**Comment by faceyspacey** [comment]
@satya164 excellent, guess I haven't checked the readme in a while. Can't wait to try it out!
