### ISSUE TITLE
Is it possible that passing param when call NavigationActions.push?

### ISSUE THREAD

**Issue by aiyidu** [exponent/ex-navigation#358]
Is it possible that passing param when call NavigationActions.push?

Like this:

this.props.navigator.push(Router.getRoute('about', {name: 'Brent'}));

But I didn't find similar api in NavigationActions.

**Comment by cem2ran** [comment]
Have you tried the following: 
`NavigationActions.push(navigatorUID, Router.getRoute('about', {name: 'Brent'}))`
https://github.com/exponent/ex-navigation#perform-navigation-actions-from-outside-of-a-component

**Comment by aiyidu** [comment]
@cem2ran 
You're right!
I am so stupid...
