### ISSUE TITLE
Passing navigator to the renderLeft method

### ISSUE THREAD

**Issue by hose314** [exponent/ex-navigation#374]
```
navigationBar: {
      ...,
      renderLeft: (route, props) => <CloseButton route={route} {...props} />
},
```
Hi there. Is there any ability to pass navigator object to the `CloseButton` component? I need this to handle `onPress` in order to pop navigator stack.
Thanks!

**Comment by hose314** [comment]
i did it with `withNavigation` decorator

**Comment by kamleshchandnani** [comment]
Can you share the snippet? I am also trying to achieve the same

**Comment by kiki-le-singe** [comment]
@hose314 have you found a solution?

thanks

**Comment by sibelius** [comment]
@kamleshchandnani @kiki-le-singe u can use something like this: https://github.com/sibelius/ex-navigation-recipes/blob/master/recipes/NavigationBarMenuButton.md

**Comment by kiki-le-singe** [comment]
@sibelius haha you are a hero. It works :)

Thanks!
