### ISSUE TITLE
Upgraded to React-Native@0.40 and getting UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by robbykim** [exponent/ex-navigation#403]
Hi, I upgraded to react-native@0.40 and am getting the following error: 

`transformed 688/689 (100%)(node:824) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 946): SyntaxError: SyntaxError /Users/robbyk/Documents/NewFoundry/umbsc/node_modules/@exponent/ex-navigation/src/ExNavigation.js: Unexpected token (34:9)
(node:824) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

When I searched the code to the line number/column in question, it leads me to this line 

`export * as NavigationStyles from './ExNavigationStyles';` 

where the 9th column is the space between * and 'as'. I'm not really sure what's going on here..

**Comment by davingreen** [comment]
Did you solve this? I'm getting a syntax error at the same line with 0.40.0

**Comment by robbykim** [comment]
yeah, my issue was accidentally replacing my babelrc file. but overall, i decided to forgo 0.40 for now and stuck with 0.39.2 because i was having issues with archiving builds
