### ISSUE TITLE
How do I jumpToTab and reset stack and push using a redux action?

### ISSUE THREAD

**Issue by mypark** [exponent/ex-navigation#408]
How do I jumpToTab and reset stack and push using a redux action?

I'm getting two errors
1. When I call NavigationActions.push `undefined is not an object (evaulating 'tabItem.element')
2. popToTop resets the navigation to the top of the previous tab selelction, not the tab I've jumped to
3. I tried using immediatelyResetStack as well but couldn't figure out how to get that working

```
import Router from '../navigation/Router';
export function test() {
  return async (dispatch, getState) => {
    dispatch(NavigationActions.jumpToTab('main', {key: 'myGames'}));
    // dispatch(NavigationActions.immediatelyResetStack('main', [Router.getRoute('myGames'), Router.getRoute('event', {eventId: 'cixtde2o50jzb0173697uufpu'})], 1));
    dispatch(NavigationActions.popToTop('main', {key: 'myGames'}));
    dispatch(NavigationActions.push('main', Router.getRoute('event', {eventId: 'foo'})));
  };
}
```

**Comment by mypark** [comment]
I was using the udid of the root navigation - I should be using the udid of each stack individually

**Comment by jasongrishkoff** [comment]
What was your final solution here? Having similar issues.
