### ISSUE TITLE
Disable Drawer on pushed route

### ISSUE THREAD

**Issue by chrissm79** [exponent/ex-navigation#46]
When I navigate away from a DrawerNavigationItem to a new route (`Router.getRoute('routeA')`) I get the back button but when I attempt to swipe to go back, it opens the drawer instead of navigating back. Clicking the back button works as expected.

**Comment by chrissm79** [comment]
Would it be possible to put "drawerLockMode" on the route config?

**Comment by brentvatne** [comment]
seems reasonable @chrissm79, I will work on that

**Comment by chrissm79** [comment]
@brentvatne Awesome, thank you!!!

**Comment by brentvatne** [comment]
Sorry for the delay on this, still thinking about it.

**Comment by chrissm79** [comment]
No worries, I took a hack at it one day but it was a little more in depth than I originally thought (if the option is available on the route). Thanks for looking into it, really enjoying the library!

**Comment by jamieathans** [comment]
@brentvatne While you are determining the best way to implement "drawerLockMode" per route etc, is it possible to release an update that passes the "drawerLockMode" prop from the ExNavigationDrawer component to the underlying react-native-drawer-layout/DrawerLayout (like has been done for "drawerWidth").

This would allow to lock/unlock the draw in response to certain application events. In my case, I do not want the user being able to slide the draw open when the app is in landscape.

**Comment by brentvatne** [comment]
@jamieathans - happy to take a PR for that, don't have time probably today or tomorrow to implement myself though

**Comment by ddolheguy** [comment]
Would really appreciate this function as it's causing issues for me when using mapping and have a user swipe on the map also causes the drawer to open which is annoying

**Comment by DomiR** [comment]
Well, how should we approach this? New action on the drawer to lock and unlock drawer, so that we can do it programatically at any time? I just can't find nice lifecyclehooks to en- and disable this (something like routWillMount would be nice).

**Comment by satya164** [comment]
I think it's a pretty common pattern to have the drawer only in the screens the open drawer button is visible, .i.e. the immediate child routes.

**Comment by ddolheguy** [comment]
To make this more "functional", could we allow a property to be added to the view route which allows the drawer to be locked (as per comments by @chrissm79) but also allow the property to be a function which could then be updated via "updateCurrentRouteParams".  Like how the title works.

It would be nice if all properties of the route could be updated via a function, but this would be a larger card.

**Comment by sibelius** [comment]
@chrissm79 @jamieathans @ddolheguy u could follow this workaround: https://github.com/exponentjs/ex-navigation/issues/89#issuecomment-254920193

**Comment by chrissm79** [comment]
@sibelius THANK YOU!!! I have no idea how I missed this comment but it's exactly what I needed and works great!

**Comment by garrettbland** [comment]
@sibelius What did you end up doing to resolve this? I'm having the same issue. I read through the comment but I guess I'm still somewhat confused. Did you use the following code below to resolve your issue?

`this.props.navigation.getNavigator('master').push(Router.getRoute('postDetail', {id}));`

**Comment by sibelius** [comment]
yep

that idea is to have a master route that has no drawer or tabs, then u push the route to it

so the view won't have tabs ou drawer on it

**Comment by garrettbland** [comment]
Gotcha! That way it doesn't even know about the drawer or tabs being on the previous route. Thanks!
